name: NodeGoat DevSecOps Pipeline

on:
  push:
    branches:
      - Dev

  pull_request:
    branches:
      - Dev

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: NodeGoat

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Show Node Version
        run: node --version

      - name: Show NPM Version
        run: npm --version

      - name: Install Dependencies
        run: npm ci